version: "3"
services:
  server:
    build: ./application-server
    image: area_server
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - back_and_db

  client_mobile:
    build: ./mobile-without-expo
    image: client_mobile
    volumes:
      - areamobile:/mobile/release

  client_web:
    build: ./web-client
    image: client_web
    depends_on:
      - server
      - database
      - client_mobile
    ports:
      - "8081:8081"
    volumes:
      - areamobile:/app/public

  database:
    image: 'mariadb:10.6.7'
    container_name: database
    ports:
      - "3306:3307"
    command: --init-file /usr/share/area/table.sql
    environment:
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_USER: "${MYSQL_ROOT_USER}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - areadb:/var/lib/mysql/
      - ./table.sql:/usr/share/area/table.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${MYSQL_ROOT_USER}", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
        - back_and_db

volumes:
  areadb:
  areamobile:

networks:
  back_and_db:
    driver: bridge
